### ISSUE TITLE
Support for existing IImage loading

### ISSUE THREAD

**Issue by ionite34** [AvaloniaUtils/AsyncImageLoader.Avalonia#17]
Is it possible to support loading an existing `Bitmap` / `IImage` if we have it? We're in a sort of unique scenario of having some images coming from remote URLs and some coming as raw bytes over websocket which we create `Bitmap` with. We've already created several derivative control templates with `AdvancedImage` and it feels like it would be messy to do some control switching with the original `Image` control to support this.

Perhaps making setting the `CurrentImage` property settable? Thanks for the library by the way, has been very helpful.

**Comment by SKProCH** [comment]
Hello, @ionite34 

Did you want this feature for AdvancedImage?

**Comment by ionite34** [comment]
> Hello, @ionite34 
> 
> Did you want this feature for AdvancedImage? 

Yes, should have specified, have some sort of settable Bitmap / IImage property that takes priority over the `Source` property for `AdvancedImage`
