### ISSUE TITLE
👍

### ISSUE THREAD

**Issue by CodeDiseaseDev** [AvaloniaUtils/AsyncImageLoader.Avalonia#21]
![image](https://github.com/AvaloniaUtils/AsyncImageLoader.Avalonia/assets/70626250/aa889fd3-6647-44ec-81a3-d893373e5cd6)

**Comment by SKProCH** [comment]
Hello. Did you install a nuget package?

**Comment by SKProCH** [comment]
Since it working as intended I've closing this. Feel free to reopen it or create a new one if the problem persists or you have any questions.
