### ISSUE TITLE
1GB+ Memory Usage

### ISSUE THREAD

**Issue by MangoDevx** [AvaloniaUtils/AsyncImageLoader.Avalonia#22]
Context: I have wrote code which allows me to flip through images like a book. There is a left/right button which changes the image source. The image source is a string which correlates to an image file path. The image source is updated from an array of strings that contains all the page file paths. Each image is about 600Kb and in a .jpg format. I have set the image loader to use the BaseWebImageLoader and I disposed of the default one.

 My issue is when I flip through my pages, my memory usage spikes from 300MB to 1GB+ then doesn't drop much when the GC cleans up. Am I abusing the library, or is there possibly already a known memory leak within the library? What can I do to remedy this? 

```cs
ViewModel
[ObservableProperty] private string imageSource;
private List<string> _pages = new();
private int _currentPage;

[RelayCommand]
public void Left() {
    _currentPage--;
    ImageSource = _pages[_currentPage];
}

[RelayCommand]
public void Right() {
    _currentPage++;
    ImageSource = _pages[_currentPage];
}
```

**Comment by SKProCH** [comment]
Hello, @MangoDevx 

The `BaseWebImageLoader` doesn't have a cache, so apparently not, this is not intended.  
Can you debug what consuming so much memory through memory analyzer (such as dotMemory)?  
Or can you please provide a minimum reproduceable example of this case so I can debug it myself?  

Also, please note what dotnet have a pretty smart GC which will not release memory ASAP. But as I mentioned earlier the BaseWebImageLoader doesn't have a cache, so I have no idea what's going wrong.

**Comment by MangoDevx** [comment]
> Hello, @MangoDevx 
> 
> 
> 
> The `BaseWebImageLoader` doesn't have a cache, so apparently not, this is not intended.  
> 
> Can you debug what consuming so much memory through memory analyzer (such as dotMemory)?  
> 
> Or can you please provide a minimum reproduceable example of this case so I can debug it myself?  
> 
> 
> 
> Also, please note what dotnet have a pretty smart GC which will not release memory ASAP. But as I mentioned earlier the BaseWebImageLoader doesn't have a cache, so I have no idea what's going wrong.

Yes, I can try to get the information you need soon.

**Comment by SKProCH** [comment]
Hmm, seems like so. Can you provide a sample project?

**Comment by MangoDevx** [comment]
> Also, you can try to resize image after downloading it, but before passing to library (and Avalonia's Image control)

My apologies, on a work trip. I think we can go ahead and close this, our team dug further into it and its stemming from some unmanaged resources floating around from Skia it looks like.

**Comment by SKProCH** [comment]
Ok, glad to hear that. If you still need help with this library feel free to reopen this issue or create another one)
