### ISSUE TITLE
Any chance to support webp?

### ISSUE THREAD

**Issue by SuperJMN** [AvaloniaUtils/AsyncImageLoader.Avalonia#25]
I don't want to miss the chance to say thank you. This project is A MUST!

**Comment by SKProCH** [comment]
Hello, @SuperJMN 

This library is built as an extension of Avalonia's Image control. So, probably webp support should be requested from Avalonia's side, as we implement only bitmap loading, sorry. 

Thanks for your appreciation!

**Comment by SKProCH** [comment]
Also, you can probably try to implement a custom loading mechanism and convert a webp to a bitmap via imagesharp or something similar, before passing to Avalonia. I think in theory this can work.
