### ISSUE TITLE
Exception when using Avalonia version 11.0.0-preview6

### ISSUE THREAD

**Issue by mkamran8** [AvaloniaUtils/AsyncImageLoader.Avalonia#8]
Hi, Thanks for this package. I am trying to update avalonia from version 11 preview 5 to 6. and getting an error in AsyncImageLoader.
The error is as follows

System.TypeInitializationException: 'The type initializer for 'AsyncImageLoader.AdvancedImage' threw an exception.'
Inner Exception
MissingMethodException: Method not found: 'Avalonia.StyledProperty`1<!!1> Avalonia.AvaloniaProperty.Register(System.String, !!1, Boolean, Avalonia.Data.BindingMode, System.Func`2<!!1,Boolean>, System.Func`3<Avalonia.AvaloniaObject,!!1,!!1>, System.Action`2<Avalonia.AvaloniaObject,Boolean>)'.

Here is how I am using the image loader
`<asyncImageLoader:AdvancedImage Source="{Binding ProfilePicUrl}" Stretch="UniformToFill" />`

Thanks

**Comment by SKProCH** [comment]
Hello, @mkamran8 

Fixed with `3.0.0-avalonia11-preview4` version. Thanks!
